name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout IWYU
        uses: actions/checkout@v4
        with:
          path: include-what-you-use

      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: clang_21
          path: llvm-project

      - name: Configure
        shell: pwsh
        run: |
          cmake `
            -S llvm-project/llvm `
            -B build `
            -G Ninja `
            -DLLVM_ENABLE_PROJECTS=clang `
            -DLLVM_EXTERNAL_PROJECTS=include-what-you-use `
            -DLLVM_EXTERNAL_INCLUDE_WHAT_YOU_USE_SOURCE_DIR="${{ github.workspace }}/include-what-you-use" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target include-what-you-use

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: include-what-you-use-windows
          path: |
            build/bin/include-what-you-use.exe
            build/**/include-what-you-use.exe